### PR TITLE
Track and restore iterator state

### PR DESCRIPTION
**Pull request by roysc**
Iterator state is tracked and stored/restored from files; implements https://github.com/vulcanize/eth-ipfs-state-validator/issues/38.

Depends on https://github.com/vulcanize/go-eth-state-node-iterator/pull/18 for tracker code.

### CODE REVIEW

**Comment by roysc** [comment]
Made some fixes after more local testing

**Review by i-norden — APPROVED** [review]
LGTM!

**Comment by i-norden** [comment]
Hey @roysc  can you merge https://github.com/vulcanize/go-eth-state-node-iterator/pull/18, update the go.mod here, and merge this? Thanks!

**Comment by i-norden** [comment]
@roysc what is this waiting on?

**Pull request merged**
