### PR TITLE
minimal workflow for future tests

### PR DESCRIPTION
**Pull request by ABastionOfSanity**
The test(s) in this repo are broken/invalid and are not run in any workflow.
This is simple "does it build" check.

### CODE REVIEW

**Comment by i-norden** [comment]
Please provide specifics of the errors you encounter on issues/PRs.

I ran the tests to find:

```
# github.com/cerc-io/eth-ipfs-state-validator/v4/pkg_test [github.com/cerc-io/eth-ipfs-state-validator/v4/pkg.test]
./validator_test.go:231:10: undefined: ResetTestDB
./validator_test.go:282:10: undefined: ResetTestDB
./validator_test.go:306:10: undefined: ResetTestDB
./validator_test.go:333:13: undefined: PublishRaw
./validator_test.go:337:13: undefined: PublishRaw
FAIL	github.com/cerc-io/eth-ipfs-state-validator/v4/pkg [build failed]
```

Which identifies the problem as the removal of these methods in https://github.com/cerc-io/eth-ipfs-state-validator/pull/45/files.

@roysc please fix this. Thanks!

**Comment by i-norden** [comment]
Nvm @roysc I got it. But please note this mistake (on my part too, as the reviewer of that PR).

**Comment by i-norden** [comment]
The build failures are due to interface changes in the new geth version, specifically:

* `trie.NewDatabase` needs to receive an `ethdb.Database` now instead of an `ethdb.KeyValueStore`
* `StateDB.OpenStorageTrie` needs to receive `(common.Hash, common.Hash, common.Hash)` args now instead of `(common.Hash, common.Hash)`

Could be worthwhile to add the github action in a separate PR to decouple it from the rebase work.

**Comment by ABastionOfSanity** [comment]
Going to recreate this patch against fixed unit tests.

**Comment by roysc** [comment]
Ah, really sorry, I forgot to add a file to git.

**Pull request closed without merging**
